### ISSUE TITLE
Doesn't work in visual studio 2017

### ISSUE THREAD

**Issue by apis3445** [SoftFluent/CodeFluent-Entities#2]
The softfluent doesn't work in visual studio 2017

**Comment by meziantou** [comment]
Which version of CodeFluent Entities are you using?
FYI, the latest release ([1.0.61214.915](http://activation.softfluent.com/activation.ashx?productName=CodeFluent%20Entities%20Enterprise%20Edition&build=1.0.61214.915)) should work with Visual Studio 2017.
